---
- hosts: node
  become: true
  vars:
    ansible_become_pass: password
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
